fixtures:
  repositories:
    stdlib:
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib'
    concat:
      repo: 'git://github.com/puppetlabs/puppetlabs-concat'
      ref: '1.2.1'
    collectd:
      repo: 'git://github.com/puppet-community/puppet-collectd'
      ref: 'v4.1.2'
  symlinks:
    collectd_plugins: "#{source_dir}"
